spring:
  application:
    name: caller
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9040/realms/demo/protocol/openid-connect/certs

server:
  port: 8040